# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "quarryio_ubuntu_vagrant"
  config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"
  
  config.vm.network :hostonly, "192.168.33.11"

  config.vm.forward_port 80, 80
  config.vm.forward_port 22, 2222

  config.vm.share_folder "quarryio", "/srv/quarryio", '../', :nfs => (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)
  config.vm.share_folder "node_modules", "/srv/node_modules", '../../', :nfs => (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/quarryio", "1"]
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/node_modules", "1"]

  config.vm.provision :salt do |salt|
    salt.run_highstate = true

    ## Optional Settings:
    # salt.minion_config = "salt/minion.conf"
    # salt.salt_install_type = "git"
    # salt.salt_install_args = "develop"

    ## Only Use these with a masterless setup to
    ## load your state tree:
    # salt.salt_file_root_path = "salt/roots/salt"
    # salt.salt_pillar_root_path = "salt/roots/pillar"

    ## If you have a remote master setup, you can add
    ## your preseeded minion key
    # salt.master = true
    # salt.minion_key = "salt/key/testing.pem"
    # salt.minion_pub = "salt/key/testing.pub"
  end
end